### ISSUE TITLE
Remanence of Previously Selected Classes

### ISSUE THREAD

**Issue by laurenrevere** [Bacaa14/Coursola#2]
If you add a class at a specific time and then later remove it, the application still behaves as if that time slot has been filled. It does not let you put a new class in that time slot. It seems as if the images are removed, but the data is not.

**Comment by Bacaa14** [comment]
LOL

**Comment by Bacaa14** [comment]
Lets be real this is still an issue.

**Comment by laurenrevere** [comment]
I was looking for richard's version apparently.

**Comment by Bacaa14** [comment]
??

**Comment by laurenrevere** [comment]
This is a web app. His is the add on. Right?

**Comment by laurenrevere** [comment]
I'm going to try to work on it, but when i find a fix I will put the issue on Richard's.

**Comment by Bacaa14** [comment]
:P

On Fri, Jun 5, 2015 at 8:56 AM, Lauren Revere notifications@github.com
wrote:

> I'm going to try to work on it, but when i find a fix I will put the issue
> on Richard's.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Bacaa14/Coursola/issues/2#issuecomment-109284366.

## 

_Alexander Baca_
Cyber Analysis Engineer
ZeroFOX | Social Risk Management
abaca@zerofox.com | 855-ZFOXFOX
